rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_edge.gemfile
cache: bundler
script: bundle exec rake
before_install:
  - gem install bundler
bundler_args: '--without local_development'
matrix:
  fast_finish: true
