language: ruby
cache: bundler

addons:
  postgresql: '9.4'

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.7

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_6.0.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

before_install:
   - gem install bundler

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  exclude:
    - rvm: 2.2.7
      gemfile: gemfiles/activerecord_6.0.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/activerecord_6.0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/activerecord_6.0.gemfile
