language: ruby
cache: bundler

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1
  - 2.0.0

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

before_install:
   - gem install bundler

script: bundle exec rake

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.0.gemfile
  fast_finish: true
