script: "cp spec/database.yml.sample spec/database.yml && bundle install && bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql
cache: bundler
bundler_args: '--without local_development'
